AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  utf8-api

  Sample SAM Template for utf8-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  utf8CharsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: utf8-api/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        utf8CharsSearch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  utf8CharsApi:
    Description: "API Gateway endpoint URL for Prod stage for this function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/"
  utf8CharsFunction:
    Description: "UTF-8 API Lambda Function ARN"
    Value: !GetAtt utf8CharsFunction.Arn
  utf8CharsFunctionIamRole:
    Description: "Implicit IAM Role created for utf8CharsFunction"
    Value: !GetAtt utf8CharsFunctionRole.Arn
